/**
 * @file attr_util.h
 * @brief
 *
 * Copyright (c) 2022 Laird Connectivity
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef __ATTR_UTIL_H__
#define __ATTR_UTIL_H__

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************/
/* Global Constants, Macros and type Definitions                                                  */
/**************************************************************************************************/
/* Allow matching for all defined attributes and not just "1" */
/* pystart - attribute present */
#define _ATTRX0 _YYYY,
#define _ATTRX1 _YYYY,
#define _ATTRX2 _YYYY,
#define _ATTRX3 _YYYY,
#define _ATTRX4 _YYYY,
#define _ATTRX5 _YYYY,
#define _ATTRX6 _YYYY,
#define _ATTRX7 _YYYY,
#define _ATTRX8 _YYYY,
#define _ATTRX9 _YYYY,
#define _ATTRX10 _YYYY,
#define _ATTRX11 _YYYY,
#define _ATTRX12 _YYYY,
#define _ATTRX13 _YYYY,
#define _ATTRX14 _YYYY,
#define _ATTRX15 _YYYY,
#define _ATTRX16 _YYYY,
#define _ATTRX17 _YYYY,
#define _ATTRX18 _YYYY,
#define _ATTRX19 _YYYY,
#define _ATTRX20 _YYYY,
#define _ATTRX21 _YYYY,
#define _ATTRX22 _YYYY,
#define _ATTRX23 _YYYY,
#define _ATTRX24 _YYYY,
#define _ATTRX25 _YYYY,
#define _ATTRX26 _YYYY,
#define _ATTRX27 _YYYY,
#define _ATTRX28 _YYYY,
#define _ATTRX29 _YYYY,
#define _ATTRX30 _YYYY,
#define _ATTRX31 _YYYY,
#define _ATTRX32 _YYYY,
#define _ATTRX33 _YYYY,
#define _ATTRX34 _YYYY,
#define _ATTRX35 _YYYY,
#define _ATTRX36 _YYYY,
#define _ATTRX37 _YYYY,
#define _ATTRX38 _YYYY,
#define _ATTRX39 _YYYY,
#define _ATTRX40 _YYYY,
#define _ATTRX41 _YYYY,
#define _ATTRX42 _YYYY,
#define _ATTRX43 _YYYY,
#define _ATTRX44 _YYYY,
#define _ATTRX45 _YYYY,
#define _ATTRX46 _YYYY,
#define _ATTRX47 _YYYY,
#define _ATTRX48 _YYYY,
#define _ATTRX49 _YYYY,
#define _ATTRX50 _YYYY,
#define _ATTRX51 _YYYY,
#define _ATTRX52 _YYYY,
#define _ATTRX53 _YYYY,
#define _ATTRX54 _YYYY,
#define _ATTRX55 _YYYY,
#define _ATTRX56 _YYYY,
#define _ATTRX57 _YYYY,
#define _ATTRX58 _YYYY,
#define _ATTRX59 _YYYY,
#define _ATTRX60 _YYYY,
#define _ATTRX61 _YYYY,
#define _ATTRX62 _YYYY,
#define _ATTRX63 _YYYY,
#define _ATTRX64 _YYYY,
#define _ATTRX65 _YYYY,
#define _ATTRX66 _YYYY,
#define _ATTRX67 _YYYY,
#define _ATTRX68 _YYYY,
#define _ATTRX69 _YYYY,
#define _ATTRX70 _YYYY,
#define _ATTRX71 _YYYY,
#define _ATTRX72 _YYYY,
#define _ATTRX73 _YYYY,
#define _ATTRX74 _YYYY,
#define _ATTRX75 _YYYY,
#define _ATTRX76 _YYYY,
#define _ATTRX77 _YYYY,
#define _ATTRX78 _YYYY,
#define _ATTRX79 _YYYY,
#define _ATTRX80 _YYYY,
#define _ATTRX81 _YYYY,
#define _ATTRX82 _YYYY,
#define _ATTRX83 _YYYY,
#define _ATTRX84 _YYYY,
#define _ATTRX85 _YYYY,
#define _ATTRX86 _YYYY,
#define _ATTRX87 _YYYY,
#define _ATTRX88 _YYYY,
#define _ATTRX89 _YYYY,
#define _ATTRX90 _YYYY,
#define _ATTRX91 _YYYY,
#define _ATTRX92 _YYYY,
#define _ATTRX93 _YYYY,
#define _ATTRX94 _YYYY,
#define _ATTRX95 _YYYY,
#define _ATTRX96 _YYYY,
#define _ATTRX97 _YYYY,
#define _ATTRX98 _YYYY,
#define _ATTRX99 _YYYY,
#define _ATTRX100 _YYYY,
#define _ATTRX101 _YYYY,
#define _ATTRX102 _YYYY,
#define _ATTRX103 _YYYY,
#define _ATTRX104 _YYYY,
#define _ATTRX105 _YYYY,
#define _ATTRX106 _YYYY,
#define _ATTRX107 _YYYY,
#define _ATTRX108 _YYYY,
#define _ATTRX109 _YYYY,
#define _ATTRX110 _YYYY,
#define _ATTRX111 _YYYY,
#define _ATTRX112 _YYYY,
#define _ATTRX113 _YYYY,
#define _ATTRX114 _YYYY,
#define _ATTRX115 _YYYY,
#define _ATTRX116 _YYYY,
#define _ATTRX117 _YYYY,
#define _ATTRX118 _YYYY,
#define _ATTRX119 _YYYY,
#define _ATTRX120 _YYYY,
#define _ATTRX121 _YYYY,
#define _ATTRX122 _YYYY,
#define _ATTRX123 _YYYY,
#define _ATTRX124 _YYYY,
#define _ATTRX125 _YYYY,
#define _ATTRX126 _YYYY,
#define _ATTRX127 _YYYY,
#define _ATTRX128 _YYYY,
#define _ATTRX129 _YYYY,
#define _ATTRX130 _YYYY,
#define _ATTRX131 _YYYY,
#define _ATTRX132 _YYYY,
#define _ATTRX133 _YYYY,
#define _ATTRX134 _YYYY,
#define _ATTRX135 _YYYY,
#define _ATTRX136 _YYYY,
#define _ATTRX137 _YYYY,
#define _ATTRX138 _YYYY,
#define _ATTRX139 _YYYY,
#define _ATTRX140 _YYYY,
#define _ATTRX141 _YYYY,
#define _ATTRX142 _YYYY,
#define _ATTRX143 _YYYY,
#define _ATTRX144 _YYYY,
#define _ATTRX145 _YYYY,
#define _ATTRX146 _YYYY,
#define _ATTRX147 _YYYY,
#define _ATTRX148 _YYYY,
#define _ATTRX149 _YYYY,
#define _ATTRX150 _YYYY,
#define _ATTRX151 _YYYY,
#define _ATTRX152 _YYYY,
#define _ATTRX153 _YYYY,
#define _ATTRX154 _YYYY,
#define _ATTRX155 _YYYY,
/* pyend */

#ifdef __cplusplus
}
#endif

#endif /* __ATTR_UTIL_H__ */
