---
openrpc: 1.2.6
info:
  title: Project_Index
  version: 0.0.2
methods:
  - $ref: ./app/attributes/app_methods.yml
  - $ref: ./../modules/lib/laird_connect/attributes/attributes/attributes_methods.yml
  - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/qrtc_mgmt_methods.yml
  - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/shell_log_mgmt_methods.yml
  - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/os_mgmt_methods.yml
  - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/os_mgmt_mcumgr_params_methods.yml
  - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/lcz_fs_mgmt_methods.yml
  - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/shell_mgmt_methods.yml
components:
  contentDescriptors:
    device_params:
      name: device_parameters
      schema:
        type: array
      x-device-parameters:
        - $ref: ./app/attributes/app_params.yml
        - $ref: ../modules/lib/laird_connect/pki_auth/attributes/params.yml
        - $ref: ../modules/lib/laird_connect/lwm2m_client/attributes/params.yml
        - $ref: ../modules/lib/laird_connect/lwm2m_firmware_update/attributes/params.yml
        - $ref: ../modules/lib/laird_connect/ble_client_device_manager/attributes/params.yml
        - $ref: ../modules/lib/laird_connect/shell_login/attributes/params.yml
