---
openrpc: 1.2.6
info:
  title: Project_Index
  version: 0.0.1
methods:
    - $ref: ./app/attributes/app_methods.yml
    - $ref: ./../modules/lib/laird_connect/attributes/attributes/attributes_methods.yml
    - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/event_manager_mgmt_methods.yml
    - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/fs_mgmt_methods.yml
    - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/qrtc_mgmt_methods.yml
    - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/shell_log_mgmt_methods.yml
components:
  contentDescriptors:
    device_params:
      name: device_parameters
      schema:
        type: array
      x-device-parameters:
        - $ref: ./app/attributes/app_params.yml
        - $ref: ./components/flags/attributes/flags_params_0.yml
        - $ref: ./components/alarms/attributes/alarms_params.yml
    device_flags:
      x-device-flags:
        - $ref: ./components/flags/input/flag_defines.yml