manifest:
  remotes:
    - name: JsmnRepo
      url-base: https://github.com/zserge
    - name: LairdProdEng
      url-base: git@git.devops.rfpros.com:prod_eng
    - name: ncs
      url-base: https://github.com/nrfconnect

  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  projects:
    - name: bt6xx_firmware
      remote: LairdProdEng
      revision: e2e471355bbb77134b6d994c1252c32ef3998f74
    - name: framework_zephyr
      path: modules/framework
      revision: ab025edc9245cedfd82c90d3054f168dd9f1f1cb
      remote: LairdProdEng
    - name: jsmn
      path: modules/jsmn
      revision: 7b6858a5855299d173c5ab2b46e611bf9961cbef
      remote: JsmnRepo
    - name: sdk-nrf
      path: nrf
      revision: v1.3.0
      remote: ncs
      clone-depth: 1
      import:
        name-blacklist:
          - canopennode
          - civetweb
          - hal_st
          - loramac-node
          - lvgl
          - net-tools
          - open-amp
          - openthread
    - name: zephyr_boards
      path: boards/arm
      revision: 115ab628907b1adbcbea2c9e3f788f9f1d5f2b99
      remote: LairdProdEng
    - name: zephyr_lib
      path: modules/zephyr_lib
      revision: c5f097b57577b7acb4ad1a819d58d8aa9ccef4f4
      remote: LairdProdEng
  self:
    path: manifest_repo

jenkins:
  version_prefix: 0.0.0
  part_number: 480-99999
