/******************************************************************************/
//!
//! @file AttributeFunctions.h
//!
//! @brief Attribute function indices
//!
//! @note psysart to pyend regions are generated by parmGenorator.py.
//!
//! Copyright (c) 2020 Laird Connectivity
//! All Rights Reserved.
/******************************************************************************/

#ifndef ATTRIBUTE_FUNCTIONS_H
#define ATTRIBUTE_FUNCTIONS_H

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************/
/* Includes                                                                   */
/******************************************************************************/

/******************************************************************************/
/* Global Constants, Macros and Type Definitions                              */
/******************************************************************************/

// pystart - attribute function definitions
#define ATTRIBUTE_FUNCTION_TABLE_SIZE 108

#define ATTRIBUTE_TOTAL_KEYWORDS 79
// pyend

/******************************************************************************/
/* Message Indices                                                            */
/******************************************************************************/
//
// These don't follow the naming convention. The names match the documentation.
//
// pystart - attribute function indices
#define ATTR_INDEX_SetSensorName                         1
#define ATTR_INDEX_SetSensorLocation                     2
#define ATTR_INDEX_SetBLEAdvertisingInterval             3
#define ATTR_INDEX_SetBLEAdvertisingDuration             4
#define ATTR_INDEX_SetBLEPasskey                         5
#define ATTR_INDEX_SetSettingsLock                       6
#define ATTR_INDEX_SetBatterySenseInterval               7
#define ATTR_INDEX_SetTemperatureSenseInterval           8
#define ATTR_INDEX_SetTemperatureAggregationValue        9
#define ATTR_INDEX_SetDigitalOutput1                     10
#define ATTR_INDEX_SetDigitalOutput2                     11
#define ATTR_INDEX_SetDigitalInput1                      12
#define ATTR_INDEX_SetDigitalInput2                      13
#define ATTR_INDEX_SetAnalogInputType                    14
#define ATTR_INDEX_SetTemperature1AlarmThreshold         15
#define ATTR_INDEX_SetTemperature2AlarmThreshold         16
#define ATTR_INDEX_SetTemperature3AlarmThreshold         17
#define ATTR_INDEX_SetTemperature4AlarmThreshold         18
#define ATTR_INDEX_SetAnalog1AlarmThresholds             19
#define ATTR_INDEX_SetAnalog2AlarmThresholds             20
#define ATTR_INDEX_SetAnalog3AlarmThresholds             21
#define ATTR_INDEX_SetAnalog4AlarmThresholds             22
#define ATTR_INDEX_SetActiveMode                         23
#define ATTR_INDEX_SetUseCodedPhy                        24
#define ATTR_INDEX_SetTxPower                            25
#define ATTR_INDEX_SetNetworkId                          26
#define ATTR_INDEX_SetConfigVersion                      27
#define ATTR_INDEX_SetHardwareVersion                    28
#define ATTR_INDEX_SetLedTest                            29
#define ATTR_INDEX_GetAllTemperature                     30
#define ATTR_INDEX_GetTemperature1                       31
#define ATTR_INDEX_GetTemperature2                       32
#define ATTR_INDEX_GetTemperature3                       33
#define ATTR_INDEX_GetTemperature4                       34
#define ATTR_INDEX_GetCurrent                            35
#define ATTR_INDEX_GetBatteryVoltage                     36
#define ATTR_INDEX_GetDigitalInputAlarms                 37
#define ATTR_INDEX_GetTemperature1Alarms                 38
#define ATTR_INDEX_GetTemperature2Alarms                 39
#define ATTR_INDEX_GetTemperature3Alarms                 40
#define ATTR_INDEX_GetTemperature4Alarms                 41
#define ATTR_INDEX_GetAnalog1Alarms                      42
#define ATTR_INDEX_GetAnalog2Alarms                      43
#define ATTR_INDEX_GetAnalog3Alarms                      44
#define ATTR_INDEX_GetAnalog4Alarms                      45
#define ATTR_INDEX_GetHardwareVersion                    46
#define ATTR_INDEX_GetFirmwareVersion                    47
#define ATTR_INDEX_GetResetReason                        48
#define ATTR_INDEX_GetBluetoothMAC                       49
#define ATTR_INDEX_GetBluetoothMTU                       50
#define ATTR_INDEX_GetFlags                              51
#define ATTR_INDEX_GetResetCount                         52
#define ATTR_INDEX_GetSensorName                         53
#define ATTR_INDEX_GetSensorLocation                     54
#define ATTR_INDEX_GetBLEAdvertisingInterval             55
#define ATTR_INDEX_GetBLEAdvertisingDuration             56
#define ATTR_INDEX_GetSettingsLock                       57
#define ATTR_INDEX_GetBatterySenseInterval               58
#define ATTR_INDEX_GetTemperatureSenseInterval           59
#define ATTR_INDEX_GetTemperatureAggregationValue        60
#define ATTR_INDEX_GetDigitalOutput1                     61
#define ATTR_INDEX_GetDigitalOutput2                     62
#define ATTR_INDEX_GetDigitalInput1                      63
#define ATTR_INDEX_GetDigitalInput2                      64
#define ATTR_INDEX_GetAnalogInput1Type                   65
#define ATTR_INDEX_GetTemperature1AlarmThreshold         66
#define ATTR_INDEX_GetTemperature2AlarmThreshold         67
#define ATTR_INDEX_GetTemperature3AlarmThreshold         68
#define ATTR_INDEX_GetTemperature4AlarmThreshold         69
#define ATTR_INDEX_GetAnalog1AlarmThresholds             70
#define ATTR_INDEX_GetAnalog2AlarmThresholds             71
#define ATTR_INDEX_GetAnalog3AlarmThresholds             72
#define ATTR_INDEX_GetAnalog4AlarmThresholds             73
#define ATTR_INDEX_GetActiveMode                         74
#define ATTR_INDEX_GetUseCodedPhy                        75
#define ATTR_INDEX_GetTxPower                            76
#define ATTR_INDEX_GetNetworkId                          77
#define ATTR_INDEX_GetConfigVersion                      78
#define ATTR_INDEX_GetMagnetState                        79
// pyend

/******************************************************************************/
/* Global Data Definitions                                                    */
/******************************************************************************/

/******************************************************************************/
/* Global Function Prototypes                                                 */
/******************************************************************************/

#ifdef __cplusplus
}
#endif

#endif //END ATTRIBUTE_FUNCTIONS_H