//=================================================================================================
//!
//! @file AttributeFunctions.h
//!
//! @brief Attibute function indices 
//!
//! @note psysart to pyend regions are generated by parmGenorator.py.
//!
//! Copyright (c) 2020 Laird Connectivity
//! All Rights Reserved.
//=================================================================================================

#ifndef ATTRIBUTE_FUNCTIONS_H
#define ATTRIBUTE_FUNCTIONS_H

#ifdef __cplusplus
extern "C" {
#endif

//=================================================================================================
// Includes
//=================================================================================================

//=================================================================================================
// Global Constants, Macros and Type Definitions
//=================================================================================================

// pystart - attribute function definitions
#define ATTRIBUTE_FUNCTION_TABLE_SIZE 61

// pyend

//=================================================================================================
// Message Indices
//=================================================================================================
//
// These don't follow the naming convention. The names match the documentation.
//
// pystart - attribute function indices
#define ATTR_INDEX_SetSensorName                         1
#define ATTR_INDEX_SetSensorLocation                     2
#define ATTR_INDEX_SetBLEAdvertisingInterval             3
#define ATTR_INDEX_SetBLEAdvertisingDuration             4
#define ATTR_INDEX_SetBLEPasskey                         5
#define ATTR_INDEX_SetSettingsLock                       6
#define ATTR_INDEX_SetBatterySenseInterval               7
#define ATTR_INDEX_SetTemperatureSenseInterval           8
#define ATTR_INDEX_SetTemperatureAggregationValue        9
#define ATTR_INDEX_SetDigitalOutput1                     10
#define ATTR_INDEX_SetDigitalOutput2                     11
#define ATTR_INDEX_SetDigitalInput1                      12
#define ATTR_INDEX_SetDigitalInput2                      13
#define ATTR_INDEX_SetAnalogInputType                    14
#define ATTR_INDEX_SetTemperatureAlarmThreshold          15
#define ATTR_INDEX_SetAnalog1AlarmThresholds             16
#define ATTR_INDEX_SetAnalog2AlarmThresholds             17
#define ATTR_INDEX_SetAnalog3AlarmThresholds             18
#define ATTR_INDEX_SetAnalog4AlarmThresholds             19
#define ATTR_INDEX_SetActiveMode                         20
#define ATTR_INDEX_SetUseCodedPhy                        21
#define ATTR_INDEX_SetTxPower                            22
#define ATTR_INDEX_SetNetworkId                          23
#define ATTR_INDEX_SetConfigVersion                      24
#define ATTR_INDEX_SetHardwareVersion                    25
#define ATTR_INDEX_SetLedTest                            26
#define ATTR_INDEX_GetTemperature                        27
#define ATTR_INDEX_GetCurrent                            28
#define ATTR_INDEX_GetBatteryVoltage                     29
#define ATTR_INDEX_GetAlarms                             30
#define ATTR_INDEX_GetHardwareVersion                    31
#define ATTR_INDEX_GetFirmwareVersion                    32
#define ATTR_INDEX_GetResetReason                        33
#define ATTR_INDEX_GetBluetoothMAC                       34
#define ATTR_INDEX_GetBluetoothMTU                       35
#define ATTR_INDEX_GetFlags                              36
#define ATTR_INDEX_GetResetCount                         37
#define ATTR_INDEX_GetSensorName                         38
#define ATTR_INDEX_GetSensorLocation                     39
#define ATTR_INDEX_GetBLEAdvertisingInterval             40
#define ATTR_INDEX_GetBLEAdvertisingDuration             41
#define ATTR_INDEX_GetSettingsLock                       42
#define ATTR_INDEX_GetBatterySenseInterval               43
#define ATTR_INDEX_GetTemperatureSenseInterval           44
#define ATTR_INDEX_GetTemperatureAggregationValue        45
#define ATTR_INDEX_GetDigitalOutput1                     46
#define ATTR_INDEX_GetDigitalOutput2                     47
#define ATTR_INDEX_GetDigitalInput1                      48
#define ATTR_INDEX_GetDigitalInput2                      49
#define ATTR_INDEX_GetAnalogInputType                    50
#define ATTR_INDEX_GetTemperatureAlarmThreshold          51
#define ATTR_INDEX_GetAnalog1AlarmThresholds             52
#define ATTR_INDEX_GetAnalog2AlarmThresholds             53
#define ATTR_INDEX_GetAnalog3AlarmThresholds             54
#define ATTR_INDEX_GetAnalog4AlarmThresholds             55
#define ATTR_INDEX_GetActiveMode                         56
#define ATTR_INDEX_GetUseCodedPhy                        57
#define ATTR_INDEX_GetTxPower                            58
#define ATTR_INDEX_GetNetworkId                          59
#define ATTR_INDEX_GetConfigVersion                      60
#define ATTR_INDEX_GetMagnetState                        61
// pyend

//=================================================================================================
// Global Data Definitions
//=================================================================================================

//=================================================================================================
// Global Function Prototypes
//=================================================================================================


#ifdef __cplusplus
}
#endif

#endif //END ATTRIBUTE_FUNCTIONS_H