/******************************************************************************/
//!
//! @file AttributeFunctions.h
//!
//! @brief Attribute function indices
//!
//! @note psysart to pyend regions are generated by parmGenorator.py.
//!
//! Copyright (c) 2020 Laird Connectivity
//! All Rights Reserved.
/******************************************************************************/

#ifndef ATTRIBUTE_FUNCTIONS_H
#define ATTRIBUTE_FUNCTIONS_H

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************/
/* Includes                                                                   */
/******************************************************************************/

/******************************************************************************/
/* Global Constants, Macros and Type Definitions                              */
/******************************************************************************/

// pystart - attribute function definitions
#define ATTRIBUTE_TABLE_SIZE 114

// pyend

/******************************************************************************/
/* Message Indices                                                            */
/******************************************************************************/
//
// These don't follow the naming convention. The names match the documentation.
//
// pystart - attribute function indices
#define ATTR_INDEX_SENSORNAME                            0
#define ATTR_INDEX_SENSORLOCATION                        1
#define ATTR_INDEX_ADVERTISINGINTERVAL                   2
#define ATTR_INDEX_ADVERTISINGDURATION                   3
#define ATTR_INDEX_PASSKEY                               4
#define ATTR_INDEX_LOCK                                  5
#define ATTR_INDEX_BATTERYSENSEINTERVAL                  6
#define ATTR_INDEX_TEMPERATURESENSEINTERVAL              7
#define ATTR_INDEX_TEMPERATUREAGGREGATIONCOUNT           8
#define ATTR_INDEX_DIGITALOUTPUT1MV                      9
#define ATTR_INDEX_DIGITALOUTPUT2MV                      10
#define ATTR_INDEX_DIGITALINPUT1                         11
#define ATTR_INDEX_DIGITALINPUT2                         12
#define ATTR_INDEX_ANALOGINPUT1TYPE                      13
#define ATTR_INDEX_ANALOGINPUT2TYPE                      14
#define ATTR_INDEX_ANALOGINPUT3TYPE                      15
#define ATTR_INDEX_ANALOGINPUT4TYPE                      16
#define ATTR_INDEX_HIGHTEMP1THRESH1                      17
#define ATTR_INDEX_HIGHTEMP1THRESH2                      18
#define ATTR_INDEX_LOWTEMP1THRESH1                       19
#define ATTR_INDEX_LOWTEMP1THRESH2                       20
#define ATTR_INDEX_TEMP1DELTATHRESH                      21
#define ATTR_INDEX_HIGHTEMP2THRESH1                      22
#define ATTR_INDEX_HIGHTEMP2THRESH2                      23
#define ATTR_INDEX_LOWTEMP2THRESH1                       24
#define ATTR_INDEX_LOWTEMP2THRESH2                       25
#define ATTR_INDEX_TEMP2DELTATHRESH                      26
#define ATTR_INDEX_HIGHTEMP3THRESH1                      27
#define ATTR_INDEX_HIGHTEMP3THRESH2                      28
#define ATTR_INDEX_LOWTEMP3THRESH1                       29
#define ATTR_INDEX_LOWTEMP3THRESH2                       30
#define ATTR_INDEX_TEMP3DELTATHRESH                      31
#define ATTR_INDEX_HIGHTEMP4THRESH1                      32
#define ATTR_INDEX_HIGHTEMP4THRESH2                      33
#define ATTR_INDEX_LOWTEMP4THRESH1                       34
#define ATTR_INDEX_LOWTEMP4THRESH2                       35
#define ATTR_INDEX_TEMP4DELTATHRESH                      36
#define ATTR_INDEX_HIGHANALOG1THRESH1                    37
#define ATTR_INDEX_HIGHANALOG1THRESH2                    38
#define ATTR_INDEX_LOWANALOG1THRESH1                     39
#define ATTR_INDEX_LOWANALOG1THRESH2                     40
#define ATTR_INDEX_ANALOG1DELTATHRESH                    41
#define ATTR_INDEX_HIGHANALOG2THRESH1                    42
#define ATTR_INDEX_HIGHANALOG2THRESH2                    43
#define ATTR_INDEX_LOWANALOG2THRESH1                     44
#define ATTR_INDEX_LOWANALOG2THRESH2                     45
#define ATTR_INDEX_ANALOG2DELTATHRESH                    46
#define ATTR_INDEX_HIGHANALOG3THRESH1                    47
#define ATTR_INDEX_HIGHANALOG3THRESH2                    48
#define ATTR_INDEX_LOWANALOG3THRESH1                     49
#define ATTR_INDEX_LOWANALOG3THRESH2                     50
#define ATTR_INDEX_ANALOG3DELTATHRESH                    51
#define ATTR_INDEX_HIGHANALOG4THRESH1                    52
#define ATTR_INDEX_HIGHANALOG4THRESH2                    53
#define ATTR_INDEX_LOWANALOG4THRESH1                     54
#define ATTR_INDEX_LOWANALOG4THRESH2                     55
#define ATTR_INDEX_ANALOG4DELTATHRESH                    56
#define ATTR_INDEX_ACTIVEMODE                            57
#define ATTR_INDEX_USECODEDPHY                           58
#define ATTR_INDEX_TXPOWER                               59
#define ATTR_INDEX_NETWORKID                             60
#define ATTR_INDEX_CONFIGVERSION                         61
#define ATTR_INDEX_CONFIGTYPE                            62
#define ATTR_INDEX_HARDWAREMINORVERSION                  63
#define ATTR_INDEX_LEDTESTACTIVE                         64
#define ATTR_INDEX_COEFFICIENT1                          65
#define ATTR_INDEX_COEFFICIENT2                          66
#define ATTR_INDEX_COEFFICIENTA                          67
#define ATTR_INDEX_COEFFICIENTB                          68
#define ATTR_INDEX_COEFFICIENTC                          69
#define ATTR_INDEX_THERMISTORINDEX                       70
#define ATTR_INDEX_TEMPERATURERESULT1                    71
#define ATTR_INDEX_TEMPERATURERESULT2                    72
#define ATTR_INDEX_TEMPERATURERESULT3                    73
#define ATTR_INDEX_TEMPERATURERESULT4                    74
#define ATTR_INDEX_BATTERYVOLTAGEMV                      75
#define ATTR_INDEX_DIGITALINPUT1ALARM                    76
#define ATTR_INDEX_DIGITALINPUT2ALARM                    77
#define ATTR_INDEX_CURRENTREADINGMA                      78
#define ATTR_INDEX_HIGHTEMPERATURE1ALARM                 79
#define ATTR_INDEX_LOWTEMPERATURE1ALARM                  80
#define ATTR_INDEX_DELTATEMPERATURE1ALARM                81
#define ATTR_INDEX_HIGHTEMPERATURE2ALARM                 82
#define ATTR_INDEX_LOWTEMPERATURE2ALARM                  83
#define ATTR_INDEX_DELTATEMPERATURE2ALARM                84
#define ATTR_INDEX_HIGHTEMPERATURE3ALARM                 85
#define ATTR_INDEX_LOWTEMPERATURE3ALARM                  86
#define ATTR_INDEX_DELTATEMPERATURE3ALARM                87
#define ATTR_INDEX_HIGHTEMPERATURE4ALARM                 88
#define ATTR_INDEX_LOWTEMPERATURE4ALARM                  89
#define ATTR_INDEX_DELTATEMPERATURE4ALARM                90
#define ATTR_INDEX_HIGHANALOG1ALARM                      91
#define ATTR_INDEX_LOWANALOG1ALARM                       92
#define ATTR_INDEX_DELTAANALOG1ALARM                     93
#define ATTR_INDEX_HIGHANALOG2ALARM                      94
#define ATTR_INDEX_LOWANALOG2ALARM                       95
#define ATTR_INDEX_DELTAANALOG2ALARM                     96
#define ATTR_INDEX_HIGHANALOG3ALARM                      97
#define ATTR_INDEX_LOWANALOG3ALARM                       98
#define ATTR_INDEX_DELTAANALOG3ALARM                     99
#define ATTR_INDEX_HIGHANALOG4ALARM                      100
#define ATTR_INDEX_LOWANALOG4ALARM                       101
#define ATTR_INDEX_DELTAANALOG4ALARM                     102
#define ATTR_INDEX_HWVERSION                             103
#define ATTR_INDEX_FIRMWAREVERSION                       104
#define ATTR_INDEX_RESETREASON                           105
#define ATTR_INDEX_BLUETOOTHADDRESS                      106
#define ATTR_INDEX_MTU                                   107
#define ATTR_INDEX_FLAGS                                 108
#define ATTR_INDEX_RESETCOUNT                            109
#define ATTR_INDEX_DIGITALINPUT1MV                       110
#define ATTR_INDEX_DIGITALINPUT2MV                       111
#define ATTR_INDEX_MAGNETSTATE                           112
#define ATTR_INDEX_BOOTLOADERVERSION                     113
// pyend

/******************************************************************************/
/* Global Data Definitions                                                    */
/******************************************************************************/

/******************************************************************************/
/* Global Function Prototypes                                                 */
/******************************************************************************/

#ifdef __cplusplus
}
#endif

#endif //END ATTRIBUTE_FUNCTIONS_H